### ISSUE TITLE
Project does not build with mvn > 3.1

### ISSUE THREAD

**Issue by jonbodner** [jdamick/nexus-gitlab-token-auth-plugin#1]
mvn clean install -DskipTests=true

[WARNING] Rule 0: org.apache.maven.plugins.enforcer.RequireMavenVersion failed with message:
Detected Maven Version: 3.2.5 is not in the allowed range [3.0.4,3.1).
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

mvn clean install -DskipTests=true -Denforcer.skip=true

[WARNING] Error injecting: org.sonatype.nexus.pluginbundle.maven.GenerateMetadataMojo
java.lang.NoClassDefFoundError: org/sonatype/aether/collection/DependencyCollectionException
at java.lang.Class.getDeclaredConstructors0(Native Method)
at java.lang.Class.privateGetDeclaredConstructors(Class.java:2532)
at java.lang.Class.getDeclaredConstructors(Class.java:1901)

**Comment by volker-fr** [comment]
Works with maven 3.0.5.

**Comment by borodaalex** [comment]
I had the same error when building custom nexus plugin:
org.apache.maven.enforcer.rule.api.EnforcerRuleException: Detected Maven Version: 3.2.5 is not in the allowed range [3.0.4,3.1).
    at org.apache.maven.plugins.enforcer.AbstractVersionEnforcer.enforceVersion(AbstractVersionEnforcer.java:106)
    at org.apache.maven.plugins.enforcer.RequireMavenVersion.execute(RequireMavenVersion.java:51)
    at org.apache.maven.plugins.enforcer.EnforceMojo.execute(EnforceMojo.java:177)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)

**Comment by borodaalex** [comment]
I've figured out - what's the reason might be:
in nexus oss they have enforce plugin that says the next:
<plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-enforcer-plugin</artifactId>
        <executions>
          <execution>
            <id>enforce-environment</id>
            <goals>
              <goal>enforce</goal>
            </goals>
            <configuration>
              <fail>true</fail>
              <rules>
                
                <requireMavenVersion>
                  <version>[3.0.4,3.1)</version>
                </requireMavenVersion>

**Comment by jdamick** [comment]
yeah.. it comes from their pom config..

**Comment by jdamick** [comment]
tied to upstream..closing
